## Data Preprocessing 

1. Train and test split
2. Categorical encoding
3. Scaling the Values
4. Saving preprocess data

In [23]:
import pandas as pd
from sklearn.model_selection import train_test_split

df = pd.read_csv("../Data/Banksim.csv")
df.head()

,step,customer,age,gender,zipcodeOri,merchant,zipMerchant,category,amount,fraud
0,0,'C1093826151','4','M','28007','M348934600','28007','es_transportation',4.55,0
1,0,'C352968107','2','M','28007','M348934600','28007','es_transportation',39.68,0
2,0,'C2054744914','4','F','28007','M1823072687','28007','es_transportation',26.89,0
3,0,'C1760612790','3','M','28007','M348934600','28007','es_transportation',17.25,0
4,0,'C757503768','5','M','28007','M348934600','28007','es_transportation',35.72,0

In [24]:
df.drop(columns =['zipcodeOri','zipMerchant'],axis=1,inplace=True)
df.head()

,step,customer,age,gender,merchant,category,amount,fraud
0,0,'C1093826151','4','M','M348934600','es_transportation',4.55,0
1,0,'C352968107','2','M','M348934600','es_transportation',39.68,0
2,0,'C2054744914','4','F','M1823072687','es_transportation',26.89,0
3,0,'C1760612790','3','M','M348934600','es_transportation',17.25,0
4,0,'C757503768','5','M','M348934600','es_transportation',35.72,0

In [25]:
X= df.drop('fraud',axis=1)
y = df['fraud']
print(X.shape,y.shape)

(594643, 7) (594643,)

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(475714, 7) (118929, 7) (475714,) (118929,)

In [27]:
X_train['customer'].nunique()

4112

In [28]:
X_train = X_train.drop(columns=["customer"])
X_test = X_test.drop(columns=["customer"])

In [29]:
numeric_features = ['step', 'amount']
categorical_features = ['age', 'gender', 'merchant', 'category']

In [30]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
encoder.fit(X_train[categorical_features])

OneHotEncoder(handle_unknown='ignore', sparse_output=False)

In [31]:
X_train_cat = encoder.transform(X_train[categorical_features])
X_test_cat = encoder.transform(X_test[categorical_features])

In [32]:
from sklearn.preprocessing import StandardScaler
scaler  = StandardScaler()
scaler.fit(X_train[numeric_features])

StandardScaler()

In [33]:
X_train_numeric  = scaler.transform(X_train[numeric_features])
X_test_numeric  = scaler.transform(X_test[numeric_features])

In [34]:
encoded_feature_names = encoder.get_feature_names_out(categorical_features)

all_feature_names = numeric_features + list(encoded_feature_names)

In [35]:
import numpy as np
X_train_processed = pd.DataFrame(
    np.hstack((X_train_numeric, X_train_cat)),
    columns=all_feature_names
)

X_test_processed = pd.DataFrame(
    np.hstack((X_test_numeric, X_test_cat)),
    columns=all_feature_names
)

In [36]:
import joblib
with open('../models/encoder.pkl','wb') as f:
    joblib.dump(encoder, f)
with open('../models/scaler.pkl','wb') as f:
    joblib.dump(scaler, f)

In [37]:
import joblib

joblib.dump(X_train_processed, "../data/X_train_processed.pkl")
joblib.dump(X_test_processed, "../data/X_test_processed.pkl")
joblib.dump(y_train, "../data/y_train.pkl")
joblib.dump(y_test, "../data/y_test.pkl")

['../data/y_test.pkl']

In [38]:
import joblib

joblib.dump(all_feature_names, "../models/feature_names.pkl")

['../models/feature_names.pkl']

# Preprocessing Summary

1. Performed stratified train-test split.
2. Applied OneHotEncoder to categorical features.
3. Applied StandardScaler to numerical features.
4. Fitted transformations only on training data.
5. Saved encoder and scaler for deployment.
6. Prepared ML-ready feature matrices.

Data is now ready for model training.